#! /bin/bash
distro=debian
app_dir="${PREFIX}/var/lib/proot-distro/installed-rootfs/${distro}/usr/share/applications/"

echo $app_dir

ls $app_dir

echo ""


if [ -n "$1" ]; then
    filename="$1"
    shift
    params="$@"
else
    read -p "Choose the .desktop filename that you want to create a shortcut for:" filename

    if [[ ! "$filename" == *.desktop ]]; then
        filename="$filename.desktop"
    fi
    read -p "Add any extra parameters e.g. --no-sandbox (optional):" params
fi
if [ ! -f ${app_dir}/${filename} ]; then
    echo "${filename} doesn't exist."
    exit 1
fi

cp ${app_dir}/${filename} ${PREFIX}/share/applications && sed -i "s/^Exec=\(.*\)$/Exec=lunix-run \1 ${params}/" ${PREFIX}/share/applications/${filename}

echo "complete"


