#!/bin/bash

if [[ $1 == "--user" ]]; then
	user=$2
	shift 2
else
	user="user"
fi

if [[ -z "$@" ]]; then
    proot-distro login fedora --shared-tmp \
    --bind ${PREFIX%/*}/home:/home/${user} \
    --user $user
else
    proot-distro login fedora --shared-tmp \
    --bind ${PREFIX%/*}/home:/home/${user} \
    --user $user -- env DISPLAY=:1 $@
fi
